#!/usr/bin/env bash
#Author: MikiasHailu

eval $("ssh-agent")
ssh-add ~/.ssh/school
ssh ubuntu@100.25.205.219
~                                                                                                                                                                       
~                          
